# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b5dec74ee612aa7f83416703a9552dd9"
name = "poll-app"
handle = "poll-app-2"
application_url = "https://bulgarian-ssl-skirt-seniors.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "zep-scule.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://bulgarian-ssl-skirt-seniors.trycloudflare.com/auth/callback",
  "https://bulgarian-ssl-skirt-seniors.trycloudflare.com/auth/shopify/callback",
  "https://bulgarian-ssl-skirt-seniors.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
